- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - Create_vm_tag_answer.yml
  tasks:
    - name: Create a new VM Tag
      nsxt_vm_tag:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        display_name: "{{ item.display_name }}"
       external_id: "{{ item.external_id | default([]) }}"
        state: "{{ item.state }}"
        validate_certs: False
      with_items:
        - "{{ nsxt_vm_tag }}"
